### ISSUE TITLE
Consensus to approve RFCs

### ISSUE THREAD

**Issue by davidwinter** [madetech/rfcs#23]
'Consensus' is quite vague currently for approving an RFC. Can we make this a little more explicit in the README so it's clearer when we feel like an RFC can be approved? I currently have an RFC with a single approval, but don't feel this warrants merging yet.

Should we say a set number of people have to approve an RFC PR for it to be possible to approve? Or at least state that silence is approval?

**Comment by StevenLeighton21** [comment]
I'd be happy with silence as tacit approval, but a minimum shelf life for an RFC perhaps?
